version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpswd
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s
  
  dashboard:
    image: iwalucas/metabase
    container_name: dashboard
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      